# Generated by Django 6.0.6 on 2026-06-11 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_registrojogada_nivel_registrojogada_operacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nome_exibicao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BancoQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('multipla_escolha', 'Múltipla Escolha'), ('completar_frase', 'Completar Frase'), ('vocabulario', 'Vocabulário'), ('classificacao', 'Classificação')], max_length=30)),
                ('enunciado', models.TextField()),
                ('resposta_correta', models.CharField(max_length=200)),
                ('dados_extras', models.JSONField(blank=True, default=dict)),
                ('ativo', models.BooleanField(default=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
            ],
        ),
    ]
