# Generated by Django 6.0.6 on 2026-06-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_disciplina_bancoquestao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrojogada',
            name='nivel',
            field=models.CharField(default='unidades', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrojogada',
            name='operacao',
            field=models.CharField(default='multiplicacao', max_length=50),
        ),
    ]
