# Generated by Django 6.0.6 on 2026-06-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_registrojogada_nivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrojogada',
            name='numero_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registrojogada',
            name='numero_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registrojogada',
            name='resposta_aluno',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
